### PR TITLE
Friendship association

### PR DESCRIPTION
**Pull request by kelibst**
milestone 5
- Create a model with associations and all requested features for friendships.
-  unit and integrations tests!
- made changes according to review

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great effort @kelibst :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

* [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  - the button on the single user page is missing
* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  - Your timeline displays posts created by all users regardless of their friendship status :warning: 
##### :hourglass:  Tests
- **[REQUIRED]** Add more tests to cover the features above and the ones that you implemented.
- **[SUGGESTION]** Use Factory bot gem for creating fixtures, it will help write clean and maintainable tests.

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hi there team :hand: 
Great job implementing some of the requested changes. :clap: :clap: :clap: 
But we still have changes to make.

- [ ] As it was pointed out in the previous review, a user can be able to reject a friendship request. Remember, when a friendship request is rejected, the row must be deleted from the database (should be covered by tests).
Screenshot from 2020-05-27 09-47-22


- [ ] I can see that you wrote some tests for the visual part of the friendship request, but we also need to write integrations tests for friendship, posts, comments and likes. This means checking if when a user creates a post/comment/like, you verify if a new post/comment/like was generated in the database.
Screenshot from 2020-05-27 09-50-09


Please kindly submit for code review again after making those changes.
Feel free to message me on Slack if you have any questions.

Happy coding :computer: 
**Sergio Torres**

**Review by nikasulo — APPROVED** [review]
# Great work! @kelibst 
Please merge and keep moving forward! I wish you the very best and see you at the top 🚀

**Comment by kelibst** [comment]
Thanks guys..

**Pull request merged**
